// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function calcPercent(score, max) {
  return score / max * 100.0;
}

exports.calcPercent = calcPercent;
/* No side effect */
