// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function discount(price, discount$1) {
  var totalDiscount = price * (discount$1 / 100.0);
  return price - totalDiscount;
}

function halfOff(param) {
  return discount(param, 50.0);
}

function tenPercentOff(param) {
  return discount(param, 10.0);
}

var totalDiscount = 100.0 * (50.0 / 100.0);

console.log("Half off of 100:", 100.0 - totalDiscount);

var totalDiscount$1 = 10.0 * (10.0 / 100.0);

console.log("10% off of 100:", 10.0 - totalDiscount$1);

exports.discount = discount;
exports.halfOff = halfOff;
exports.tenPercentOff = tenPercentOff;
/*  Not a pure module */
