// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log("Prix avant réduction: " + (String(123) + " €"));

console.log("Prix après réduction: " + (String(12.2) + " €"));

var total = 123;

var afterDiscount = 12.2;

exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
