// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function price(size) {
  if (size !== undefined) {
    var match = size;
    if (typeof match === "number") {
      switch (match) {
        case 0 : 
            return 11.00;
        case 1 : 
            return 12.50;
        case 2 : 
            return 14.00;
        
      }
    } else {
      return 16.00 + (match[0] - 1 | 0) * 0.50;
    }
  }
  
}

function shirtSizeOfString(str) {
  switch (str) {
    case "L" : 
        return /* Large */2;
    case "M" : 
        return /* Medium */1;
    case "S" : 
        return /* Small */0;
    case "XL" : 
        return /* XLarge */[1];
    case "XXL" : 
        return /* XLarge */[2];
    case "XXXL" : 
        return /* XLarge */[3];
    case "XXXXL" : 
        return /* XLarge */[4];
    default:
      return undefined;
  }
}

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

function displayedPrice(input) {
  var size = shirtSizeOfString(input);
  var amount = price(size);
  if (amount !== undefined) {
    var costStr = amount.toFixed(2);
    console.log("Your " + (String(input) + (" shirt costs \$" + (String(costStr) + "."))));
    return /* () */0;
  } else {
    console.log("Cannot determine price for " + (String(input) + ""));
    return /* () */0;
  }
}

displayedPrice("XXL");

var mySize = /* Medium */1;

var bigSize = /* XLarge */[1];

var veryBigSize = /* XLarge */[3];

exports.mySize = mySize;
exports.bigSize = bigSize;
exports.veryBigSize = veryBigSize;
exports.price = price;
exports.shirtSizeOfString = shirtSizeOfString;
exports.toFixed = toFixed;
exports.displayedPrice = displayedPrice;
/*  Not a pure module */
