// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var total = 7.0 * 14.5;

console.log("The total price is $", total);

var qty = 7.0;

var price = 14.5;

exports.qty = qty;
exports.price = price;
exports.total = total;
/*  Not a pure module */
