// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var result = 13.12 + 0.6215 * 5.0 - 11.37 * Math.pow(20.0, 0.16) + 0.3965 * 5.0 * Math.pow(20.0, 0.16);

console.log("At temperature 5 degrees C and wind speed 20 km/hr,\nthe wind chill temperature is " + (String(result) + ""));

var temperature = 5.0;

var velocity = 20.0;

exports.temperature = temperature;
exports.velocity = velocity;
exports.result = result;
/* result Not a pure module */
